# Use postgres/example user/password credentials
version: '3.4'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/discord_bot
      POSTGRES_USER: rafiwts
      POSTGRES_PASSWORD: Batory13!
      POSTGRES_DB: discord_bot